import type { LayerConfig, Categoria } from '../types'

export const CATEGORIAS: Record<Categoria, { label: string; color: string; icono: string; descripcion: string }> = {
  actores: {
    label: 'Actores Sociales',
    color: '#6D4C41',
    icono: 'users',
    descripcion: 'Comunidades, ONGs, líderes y organizaciones con presencia en los ecosistemas de Sevilla',
  },
  agua: {
    label: 'Agua',
    color: '#2E86C1',
    icono: 'droplet',
    descripcion: 'Cuencas, ríos, humedales y sistemas de monitoreo hídrico del municipio',
  },
  biodiversidad: {
    label: 'Biodiversidad',
    color: '#2D6A4F',
    icono: 'leaf',
    descripcion: 'Ecosistemas, coberturas del suelo, páramos, áreas protegidas y registros de especies',
  },
  clima: {
    label: 'Cambio Climático',
    color: '#F39C12',
    icono: 'cloud',
    descripcion: 'Estaciones hidroclimatológicas, isoyetas y pisos térmicos del territorio',
  },
  suelos: {
    label: 'Suelos',
    color: '#8B6914',
    icono: 'layers',
    descripcion: 'Conflictos de uso del suelo y su relación con las actividades productivas',
  },
  territorio: {
    label: 'Territorio',
    color: '#1B4F72',
    icono: 'map-pin',
    descripcion: 'División político-administrativa, resguardos indígenas y Paisaje Cultural Cafetero',
  },
}

export const LAYERS: LayerConfig[] = [
  // ── ACTORES SOCIALES ────────────────────────────────────────────────────────
  {
    id: 'actores_humedales',
    nombre: 'Actores — Humedales',
    categoria: 'actores',
    tipo: 'geojson',
    url: '/data/actores/actores_humedales.json',
    estilo: { color: '#6D4C41', fillColor: '#6D4C41', fillOpacity: 0.7, weight: 1.5, radius: 8 },
    visibleDefault: false,
    fichaId: 'actores_humedales',
    atributosPopup: ['nombre', 'tipo_actor', 'ecosistema', 'contacto'],
    miniatura: '/images/actores/humedales_thumb.webp',
    descripcionBreve: 'ONGs, comunidades y líderes con incidencia en los humedales de Sevilla',
  },
  {
    id: 'actores_paramo',
    nombre: 'Actores — Páramo',
    categoria: 'actores',
    tipo: 'geojson',
    url: '/data/actores/actores_paramo.json',
    estilo: { color: '#6D4C41', fillColor: '#8D6E63', fillOpacity: 0.7, weight: 1.5, radius: 8 },
    visibleDefault: false,
    fichaId: 'actores_paramo',
    atributosPopup: ['nombre', 'vereda', 'tipo_actor'],
    miniatura: '/images/actores/paramo_thumb.webp',
    descripcionBreve: 'Comunidades de páramo de Chili-Barragán y Las Hermosas',
  },
  {
    id: 'actores_bosque_andino',
    nombre: 'Actores — Bosque Andino',
    categoria: 'actores',
    tipo: 'geojson',
    url: '/data/actores/actores_bosque_andino.json',
    estilo: { color: '#5D4037', fillColor: '#5D4037', fillOpacity: 0.7, weight: 1.5, radius: 8 },
    visibleDefault: false,
    fichaId: 'actores_bosque_andino',
    atributosPopup: ['nombre', 'rol', 'predio'],
    miniatura: '/images/actores/bosque_andino_thumb.webp',
    descripcionBreve: 'Academia, ONGs, propietarios de reservas y sector productivo en zona andina',
  },
  {
    id: 'actores_bosque_seco',
    nombre: 'Actores — Bosque Seco',
    categoria: 'actores',
    tipo: 'geojson',
    url: '/data/actores/actores_bosque_seco.json',
    estilo: { color: '#4E342E', fillColor: '#4E342E', fillOpacity: 0.7, weight: 1.5, radius: 8 },
    visibleDefault: false,
    fichaId: 'actores_bosque_seco',
    atributosPopup: ['nombre', 'sector', 'municipio'],
    miniatura: '/images/actores/bosque_seco_thumb.webp',
    descripcionBreve: 'Entes gubernamentales, JAC, juntas de acueducto y sector productivo en zona seca',
  },

  // ── AGUA ────────────────────────────────────────────────────────────────────
  {
    id: 'agua_cuencas',
    nombre: 'Cuencas Hidrográficas',
    categoria: 'agua',
    tipo: 'geojson',
    url: '/data/agua/cuencas.json',
    estilo: { color: '#1E88E5', fillColor: '#42A5F5', fillOpacity: 0.35, weight: 2 },
    visibleDefault: true,
    fichaId: 'agua_cuencas',
    atributosPopup: ['nombre', 'area_ha', 'rio_principal'],
    miniatura: '/images/agua/cuencas_thumb.webp',
    descripcionBreve: 'Ríos Bugalagrande, La Paila, La Vieja y quebrada Las Cañas',
  },
  {
    id: 'agua_red_hidrica',
    nombre: 'Red Hídrica',
    categoria: 'agua',
    tipo: 'wms',
    url: 'https://geoservicios.igac.gov.co/geoserver/wms',
    wmsLayers: 'igac:red_hidrica',
    wmsFormat: 'image/png',
    visibleDefault: false,
    fichaId: 'agua_red_hidrica',
    miniatura: '/images/agua/red_hidrica_thumb.webp',
    descripcionBreve: 'Ríos, quebradas y cuerpos de agua superficial',
  },
  {
    id: 'agua_humedales',
    nombre: 'Humedales',
    categoria: 'agua',
    tipo: 'geojson',
    url: '/data/agua/humedales.json',
    estilo: { color: '#0277BD', fillColor: '#29B6F6', fillOpacity: 0.45, weight: 1.5 },
    visibleDefault: false,
    fichaId: 'agua_humedales',
    atributosPopup: ['nombre', 'tipo', 'area_ha', 'estado_conservacion'],
    miniatura: '/images/agua/humedales_thumb.webp',
    descripcionBreve: 'Humedales y lagunas del municipio de Sevilla',
  },
  {
    id: 'agua_calidad',
    nombre: 'Calidad del Agua',
    categoria: 'agua',
    tipo: 'geojson',
    url: '/data/agua/calidad_agua.json',
    estilo: { color: '#006064', fillColor: '#00ACC1', fillOpacity: 0.8, weight: 1.5, radius: 10 },
    visibleDefault: false,
    fichaId: 'agua_calidad',
    atributosPopup: ['codigo', 'parametros', 'fecha_muestreo'],
    miniatura: '/images/agua/calidad_thumb.webp',
    descripcionBreve: 'Estaciones de muestreo Quebrada San José',
  },
  {
    id: 'agua_monitoreo_subterraneo',
    nombre: 'Monitoreo Subterráneo',
    categoria: 'agua',
    tipo: 'geojson',
    url: '/data/agua/monitoreo_subterraneo.json',
    estilo: { color: '#01579B', fillColor: '#039BE5', fillOpacity: 0.9, weight: 2, radius: 10 },
    visibleDefault: false,
    fichaId: 'agua_monitoreo_subterraneo',
    atributosPopup: ['profundidad', 'nivel_freatico'],
    miniatura: '/images/agua/monitoreo_thumb.webp',
    descripcionBreve: 'Pozo de monitoreo vs-pm-1',
  },
  {
    id: 'agua_predios_art111',
    nombre: 'Predios Art. 111 Ley 99/93',
    categoria: 'agua',
    tipo: 'geojson',
    url: '/data/agua/predios_art111.json',
    estilo: { color: '#1565C0', fillColor: '#1E88E5', fillOpacity: 0.3, weight: 2 },
    visibleDefault: false,
    fichaId: 'agua_predios_art111',
    atributosPopup: ['predio', 'area_ha', 'fuente_hidrica_protegida'],
    miniatura: '/images/agua/predios_thumb.webp',
    descripcionBreve: 'Predios adquiridos para protección de cuencas',
  },

  // ── BIODIVERSIDAD ───────────────────────────────────────────────────────────
  {
    id: 'biodiversidad_cobertura_50k',
    nombre: 'Cobertura Uso Suelo 50K',
    categoria: 'biodiversidad',
    tipo: 'wms',
    url: 'https://geoservicios.igac.gov.co/arcgis/services/igac_cobertura_tierra/MapServer/WMSServer',
    wmsLayers: 'Cobertura_Tierra_2022',
    wmsFormat: 'image/png',
    visibleDefault: false,
    fichaId: 'biodiversidad_cobertura',
    miniatura: '/images/biodiversidad/cobertura_thumb.webp',
    descripcionBreve: 'CORINE Land Cover: superficies construidas, plantadas y naturales',
  },
  {
    id: 'biodiversidad_ecosistemas',
    nombre: 'Ecosistemas y Fragmentación',
    categoria: 'biodiversidad',
    tipo: 'wms',
    url: 'https://geoservicios.cvc.gov.co/geoserver/wms',
    wmsLayers: 'cvc:ecosistemas_fragmentacion',
    wmsFormat: 'image/png',
    visibleDefault: false,
    fichaId: 'biodiversidad_ecosistemas',
    miniatura: '/images/biodiversidad/ecosistemas_thumb.webp',
    descripcionBreve: 'Tipo de ecosistema e índice de fragmentación (1-5)',
  },
  {
    id: 'biodiversidad_paramos',
    nombre: 'Páramos',
    categoria: 'biodiversidad',
    tipo: 'geojson',
    url: '/data/biodiversidad/paramos.json',
    estilo: { color: '#2E7D32', fillColor: '#66BB6A', fillOpacity: 0.35, weight: 2 },
    visibleDefault: false,
    fichaId: 'biodiversidad_paramos',
    atributosPopup: ['nombre_complejo', 'area_ha', 'altitud_rango'],
    miniatura: '/images/biodiversidad/paramos_thumb.webp',
    descripcionBreve: 'Complejos de páramo Chili-Barragán y Las Hermosas',
  },
  {
    id: 'biodiversidad_especies',
    nombre: 'Registro de Especies',
    categoria: 'biodiversidad',
    tipo: 'geojson',
    url: '/data/biodiversidad/especies.json',
    estilo: { color: '#1B5E20', fillColor: '#43A047', fillOpacity: 0.85, weight: 1, radius: 7 },
    visibleDefault: false,
    fichaId: 'biodiversidad_especies',
    atributosPopup: ['nombre_cientifico', 'familia', 'fecha_registro', 'fuente'],
    miniatura: '/images/biodiversidad/especies_thumb.webp',
    descripcionBreve: 'Ocurrencias de flora y fauna en Sevilla (GBIF/SiB Colombia)',
  },
  {
    id: 'biodiversidad_areas_protegidas',
    nombre: 'Áreas Protegidas',
    categoria: 'biodiversidad',
    tipo: 'geojson',
    url: '/data/biodiversidad/areas_protegidas.json',
    estilo: { color: '#33691E', fillColor: '#8BC34A', fillOpacity: 0.3, weight: 2 },
    visibleDefault: false,
    fichaId: 'biodiversidad_areas_protegidas',
    atributosPopup: ['nombre', 'categoria', 'area_ha', 'fecha_declaracion'],
    miniatura: '/images/biodiversidad/areas_protegidas_thumb.webp',
    descripcionBreve: 'Reserva Forestal Ley 2ª/1959 y DRMI',
  },
  {
    id: 'biodiversidad_zonificacion_forestal',
    nombre: 'Zonificación Forestal',
    categoria: 'biodiversidad',
    tipo: 'wms',
    url: 'https://geoservicios.igac.gov.co/geoserver/wms',
    wmsLayers: 'igac:zonificacion_forestal',
    wmsFormat: 'image/png',
    visibleDefault: false,
    fichaId: 'biodiversidad_zonificacion_forestal',
    miniatura: '/images/biodiversidad/zonificacion_thumb.webp',
    descripcionBreve: 'Uso potencial del suelo en zonas forestales',
  },

  // ── CAMBIO CLIMÁTICO ────────────────────────────────────────────────────────
  {
    id: 'clima_isoyetas',
    nombre: 'Isoyetas de Precipitación',
    categoria: 'clima',
    tipo: 'wms',
    url: 'https://geoserver.ideam.gov.co/geoserver/ows',
    wmsLayers: 'ideam:isoyetas_multianuales',
    wmsFormat: 'image/png',
    visibleDefault: false,
    fichaId: 'clima_isoyetas',
    miniatura: '/images/clima/isoyetas_thumb.webp',
    descripcionBreve: 'Isoyetas multianuales 2016 — zonas Cauca y Pacífico',
  },
  {
    id: 'clima_estaciones',
    nombre: 'Estaciones Hidroclimatológicas',
    categoria: 'clima',
    tipo: 'geojson',
    url: '/data/clima/estaciones_hidroclimatologicas.json',
    estilo: { color: '#E65100', fillColor: '#FF9800', fillOpacity: 0.9, weight: 2, radius: 10 },
    visibleDefault: false,
    fichaId: 'clima_estaciones',
    atributosPopup: ['codigo', 'tipo', 'entidad', 'series_hist'],
    miniatura: '/images/clima/estaciones_thumb.webp',
    descripcionBreve: 'Red de monitoreo climático y limnigráfico',
  },
  {
    id: 'clima_pisos_termicos',
    nombre: 'Pisos Térmicos',
    categoria: 'clima',
    tipo: 'wms',
    url: 'https://geoservicios.igac.gov.co/geoserver/wms',
    wmsLayers: 'igac:pisos_termicos_100k',
    wmsFormat: 'image/png',
    visibleDefault: false,
    fichaId: 'clima_pisos_termicos',
    miniatura: '/images/clima/pisos_termicos_thumb.webp',
    descripcionBreve: 'Cálido, medio, frío, muy frío y extremadamente frío en Sevilla',
  },

  // ── SUELOS ──────────────────────────────────────────────────────────────────
  {
    id: 'suelos_conflictos_uso',
    nombre: 'Conflictos de Uso del Suelo',
    categoria: 'suelos',
    tipo: 'wms',
    url: 'https://geoservicios.igac.gov.co/geoserver/wms',
    wmsLayers: 'igac:conflictos_uso_suelo_50k',
    wmsFormat: 'image/png',
    visibleDefault: false,
    fichaId: 'suelos_conflictos_uso',
    miniatura: '/images/suelos/conflictos_thumb.webp',
    descripcionBreve: 'Alto conflicto, moderado, sin conflicto y zona urbana',
  },

  // ── TERRITORIO ADMINISTRATIVO ────────────────────────────────────────────────
  {
    id: 'territorio_division',
    nombre: 'División Político-Administrativa',
    categoria: 'territorio',
    tipo: 'geojson',
    url: '/data/territorio/division_administrativa.json',
    estilo: { color: '#3949AB', fillColor: '#5C6BC0', fillOpacity: 0.1, weight: 2, dashArray: '4' },
    visibleDefault: true,
    fichaId: 'territorio_division',
    atributosPopup: ['nombre_vereda', 'codigo_dane', 'area_km2'],
    miniatura: '/images/territorio/division_thumb.webp',
    descripcionBreve: 'Límite del municipio, veredas y corregimientos',
  },
  {
    id: 'territorio_resguardos',
    nombre: 'Resguardos Indígenas',
    categoria: 'territorio',
    tipo: 'geojson',
    url: '/data/territorio/resguardos.json',
    estilo: { color: '#1A237E', fillColor: '#3F51B5', fillOpacity: 0.3, weight: 2 },
    visibleDefault: false,
    fichaId: 'territorio_resguardos',
    atributosPopup: ['nombre', 'pueblo', 'area_ha', 'resolucion'],
    miniatura: '/images/territorio/resguardos_thumb.webp',
    descripcionBreve: 'Resguardo Indígena Ancore Drua',
  },
  {
    id: 'territorio_pcc',
    nombre: 'Paisaje Cultural Cafetero',
    categoria: 'territorio',
    tipo: 'geojson',
    url: '/data/territorio/pcc.json',
    estilo: { color: '#283593', fillColor: '#7986CB', fillOpacity: 0.25, weight: 2 },
    visibleDefault: false,
    fichaId: 'territorio_pcc',
    atributosPopup: ['categoria', 'area_ha', 'anno_declaracion'],
    miniatura: '/images/territorio/pcc_thumb.webp',
    descripcionBreve: 'Zona declarada Patrimonio Cultural de la Humanidad (UNESCO 2011)',
  },
]

export const MAPA_BASE_URLS = {
  osm: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
  esri: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
  topo: 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
  dark: 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',
}

export const MAPA_BASE_ATTRIBUTION = {
  osm: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
  esri: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community',
  topo: 'Map data: &copy; OpenStreetMap contributors, SRTM | Map style: &copy; OpenTopoMap (CC-BY-SA)',
  dark: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
}

export const SEVILLA_CENTER: [number, number] = [4.2710, -75.9366]
export const SEVILLA_DEFAULT_ZOOM = 13
export const SEVILLA_MIN_ZOOM = 10
export const SEVILLA_MAX_ZOOM = 18
export const SEVILLA_BOUNDS: [[number, number], [number, number]] = [
  [4.10, -76.08],
  [4.44, -75.78],
]
